name: Foreign Repo

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (not foreign repo)
        uses: actions/checkout@v5
        with:
          path: main
      # - name: Checkout (foreign repo)
      #   uses: actions/checkout@v5
      #   with:
      #     repository: software-mansion/TypeGPU
      #     path: typegpu

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
