name: Foreign Repo

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (not foreign repo)
        uses: actions/checkout@master
      - name: Checkout (foreign repo)
        uses: actions/checkout@master
        with:
          repository: software-mansion/TypeGPU
          ref: refs/heads/main
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@master
